### ISSUE TITLE
Open IDE Button not there

### ISSUE THREAD

**Issue by tedsazon** [learn-co-curriculum/js-node-practice-lab#18]
another lesson where the button is missing

**Comment by fcorreia3** [comment]
I opened the lesson in a new tab so I could follow, then went back to the other tab and opened the IDE from the previous lab, created a new folder and did the coding there. Because there are other variables called "name" and "height" in the index file that we were supposed to use, I just created name1 and height1. Then submitted the lesson.

**Comment by zaheerkth** [comment]
Lesson name: Node Practice. 

button for the IDE is missing.

**Comment by maxwellbenton** [comment]
Hi @tedsazon, 

Thank you for opening this issue and providing feedback. We've recently updated this lab and confirmed that the Open IDE button now appears and is forking down and opening as expected.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know of your experience so we can improve our content for future students.

Thank you!
